# 测试环境配置
spring:
  config:
    # 前面是启动类读取配置文件的路径，后面是测试类读取配置文件的路径
    # 写法不同，但指向同个文件，原因未知
    import:
      - optional:file:.env.test[.properties]
      - optional:file:../.env.test[.properties]
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/${DATABASE_NAME}?characterEncoding=UTF8&serverTimezone=UTC&allowMultiQueries=true&useAffectedRows=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  redis:
    host: ${REDIS_HOST}
    port: 6379
    password: ${REDIS_PASSWORD}

# 自定义配置
snapvids:
  jwt:
    secret: ${JWT_SECRET}
    expired-in-seconds: 2_592_000_000 # 默认 30 天