spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    encoding: UTF-8
    locations: classpath:database
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    # 取消将 session 持续到视图层
    open-in-view: false

# 开发环境配置文件导入
---
spring:
  config:
    activate:
      on-profile: dev
    import: application-infrastructure-dev.yaml
---

# 生产环境配置文件导入
---
spring:
  config:
    activate:
      on-profile: prod
    import: application-infrastructure-prod.yaml
---

# 测试环境配置文件导入
---
spring:
  config:
    activate:
      on-profile: test
    import: application-infrastructure-test.yaml
---