# 通用配置
server:
  servlet:
    context-path: /api
spring:
  profiles:
    active: @profileActive@
    include: infrastructure
  banner:
    location: classpath:static/banner.txt
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

logging:
  config: classpath:config/logback-spring.xml