# 通用配置
server:
  servlet:
    context-path: /api
spring:
  profiles:
    active: @profileActive@
    include: infrastructure
  banner:
    location: classpath:static/banner.txt

logging:
  config: classpath:config/logback-spring.xml